//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSample.ServiceReferencePMTBitMapWebService_test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uilogic.dp.toml.com/", ConfigurationName="ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService")]
    public interface InvokePMTBitMapWebService {
        
        // CODEGEN: Generating message contract since element name requestparameters from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIResponse invokeRefundAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPI request);
        
        // CODEGEN: Generating message contract since element name requestparameters from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIResponse invokeQueryAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPI request);
        
        // CODEGEN: Generating message contract since element name requestparameters from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIResponse invokeSettlementAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPI request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRefundAPI {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeRefundAPI", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIBody Body;
        
        public invokeRefundAPI() {
        }
        
        public invokeRefundAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeRefundAPIBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestparameters;
        
        public invokeRefundAPIBody() {
        }
        
        public invokeRefundAPIBody(string requestparameters) {
            this.requestparameters = requestparameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRefundAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeRefundAPIResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIResponseBody Body;
        
        public invokeRefundAPIResponse() {
        }
        
        public invokeRefundAPIResponse(PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeRefundAPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public invokeRefundAPIResponseBody() {
        }
        
        public invokeRefundAPIResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeQueryAPI {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeQueryAPI", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIBody Body;
        
        public invokeQueryAPI() {
        }
        
        public invokeQueryAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeQueryAPIBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestparameters;
        
        public invokeQueryAPIBody() {
        }
        
        public invokeQueryAPIBody(string requestparameters) {
            this.requestparameters = requestparameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeQueryAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeQueryAPIResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIResponseBody Body;
        
        public invokeQueryAPIResponse() {
        }
        
        public invokeQueryAPIResponse(PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeQueryAPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public invokeQueryAPIResponseBody() {
        }
        
        public invokeQueryAPIResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSettlementAPI {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSettlementAPI", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIBody Body;
        
        public invokeSettlementAPI() {
        }
        
        public invokeSettlementAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeSettlementAPIBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestparameters;
        
        public invokeSettlementAPIBody() {
        }
        
        public invokeSettlementAPIBody(string requestparameters) {
            this.requestparameters = requestparameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeSettlementAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="invokeSettlementAPIResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIResponseBody Body;
        
        public invokeSettlementAPIResponse() {
        }
        
        public invokeSettlementAPIResponse(PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class invokeSettlementAPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public invokeSettlementAPIResponseBody() {
        }
        
        public invokeSettlementAPIResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvokePMTBitMapWebServiceChannel : PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokePMTBitMapWebServiceClient : System.ServiceModel.ClientBase<PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService>, PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService {
        
        public InvokePMTBitMapWebServiceClient() {
        }
        
        public InvokePMTBitMapWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvokePMTBitMapWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokePMTBitMapWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokePMTBitMapWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIResponse PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService.invokeRefundAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPI request) {
            return base.Channel.invokeRefundAPI(request);
        }
        
        public string invokeRefundAPI(string requestparameters) {
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPI inValue = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPI();
            inValue.Body = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIBody();
            inValue.Body.requestparameters = requestparameters;
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeRefundAPIResponse retVal = ((PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService)(this)).invokeRefundAPI(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIResponse PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService.invokeQueryAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPI request) {
            return base.Channel.invokeQueryAPI(request);
        }
        
        public string invokeQueryAPI(string requestparameters) {
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPI inValue = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPI();
            inValue.Body = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIBody();
            inValue.Body.requestparameters = requestparameters;
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeQueryAPIResponse retVal = ((PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService)(this)).invokeQueryAPI(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIResponse PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService.invokeSettlementAPI(PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPI request) {
            return base.Channel.invokeSettlementAPI(request);
        }
        
        public string invokeSettlementAPI(string requestparameters) {
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPI inValue = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPI();
            inValue.Body = new PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIBody();
            inValue.Body.requestparameters = requestparameters;
            PGSample.ServiceReferencePMTBitMapWebService_test.invokeSettlementAPIResponse retVal = ((PGSample.ServiceReferencePMTBitMapWebService_test.InvokePMTBitMapWebService)(this)).invokeSettlementAPI(inValue);
            return retVal.Body.@return;
        }
    }
}
