//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSample.ServiceReferenceInvokeEcomWebServices_live {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uilogic.dp.toml.com/", ConfigurationName="ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices")]
    public interface InvokeEcomWebServices {
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSResponse InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSResponse InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWS request);
        
        // CODEGEN: Generating message contract since element name requestParameter from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSResponse InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSResponse InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSResponse InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSResponse InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSResponse InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeReversalWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeReversalWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSBody Body;
        
        public InvokeReversalWS() {
        }
        
        public InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeReversalWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amount;
        
        public InvokeReversalWSBody() {
        }
        
        public InvokeReversalWSBody(string merchantId, string atrn, string amount) {
            this.merchantId = merchantId;
            this.atrn = atrn;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeReversalWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeReversalWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSResponseBody Body;
        
        public InvokeReversalWSResponse() {
        }
        
        public InvokeReversalWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeReversalWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeReversalWSResponseBody() {
        }
        
        public InvokeReversalWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeVoidWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeVoidWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSBody Body;
        
        public InvokeVoidWS() {
        }
        
        public InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeVoidWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeVoidWSBody() {
        }
        
        public InvokeVoidWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeVoidWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeVoidWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSResponseBody Body;
        
        public InvokeVoidWSResponse() {
        }
        
        public InvokeVoidWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeVoidWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeVoidWSResponseBody() {
        }
        
        public InvokeVoidWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeBitMapQueryWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeBitMapQueryWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSBody Body;
        
        public InvokeBitMapQueryWS() {
        }
        
        public InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeBitMapQueryWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestParameter;
        
        public InvokeBitMapQueryWSBody() {
        }
        
        public InvokeBitMapQueryWSBody(string requestParameter) {
            this.requestParameter = requestParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeBitMapQueryWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeBitMapQueryWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSResponseBody Body;
        
        public InvokeBitMapQueryWSResponse() {
        }
        
        public InvokeBitMapQueryWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeBitMapQueryWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeBitMapQueryWSResponseBody() {
        }
        
        public InvokeBitMapQueryWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSBody Body;
        
        public InvokeQueryWS() {
        }
        
        public InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txntype;
        
        public InvokeQueryWSBody() {
        }
        
        public InvokeQueryWSBody(string merchantId, string orderNumber, string atrn, string txntype) {
            this.merchantId = merchantId;
            this.orderNumber = orderNumber;
            this.atrn = atrn;
            this.txntype = txntype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSResponseBody Body;
        
        public InvokeQueryWSResponse() {
        }
        
        public InvokeQueryWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeQueryWSResponseBody() {
        }
        
        public InvokeQueryWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokePartialCaptureWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokePartialCaptureWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSBody Body;
        
        public InvokePartialCaptureWS() {
        }
        
        public InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokePartialCaptureWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amount;
        
        public InvokePartialCaptureWSBody() {
        }
        
        public InvokePartialCaptureWSBody(string merchantId, string atrn, string amount) {
            this.merchantId = merchantId;
            this.atrn = atrn;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokePartialCaptureWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokePartialCaptureWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSResponseBody Body;
        
        public InvokePartialCaptureWSResponse() {
        }
        
        public InvokePartialCaptureWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokePartialCaptureWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokePartialCaptureWSResponseBody() {
        }
        
        public InvokePartialCaptureWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeCaptureWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeCaptureWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSBody Body;
        
        public InvokeCaptureWS() {
        }
        
        public InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeCaptureWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeCaptureWSBody() {
        }
        
        public InvokeCaptureWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeCaptureWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeCaptureWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSResponseBody Body;
        
        public InvokeCaptureWSResponse() {
        }
        
        public InvokeCaptureWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeCaptureWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeCaptureWSResponseBody() {
        }
        
        public InvokeCaptureWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeFullAuthReversalWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeFullAuthReversalWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSBody Body;
        
        public InvokeFullAuthReversalWS() {
        }
        
        public InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeFullAuthReversalWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeFullAuthReversalWSBody() {
        }
        
        public InvokeFullAuthReversalWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeFullAuthReversalWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeFullAuthReversalWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSResponseBody Body;
        
        public InvokeFullAuthReversalWSResponse() {
        }
        
        public InvokeFullAuthReversalWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeFullAuthReversalWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeFullAuthReversalWSResponseBody() {
        }
        
        public InvokeFullAuthReversalWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvokeEcomWebServicesChannel : PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokeEcomWebServicesClient : System.ServiceModel.ClientBase<PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices>, PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices {
        
        public InvokeEcomWebServicesClient() {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokeEcomWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWS request) {
            return base.Channel.InvokeReversalWS(request);
        }
        
        public string InvokeReversalWS(string merchantId, string atrn, string amount) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            inValue.Body.amount = amount;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeReversalWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeReversalWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWS request) {
            return base.Channel.InvokeVoidWS(request);
        }
        
        public string InvokeVoidWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeVoidWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeVoidWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWS request) {
            return base.Channel.InvokeBitMapQueryWS(request);
        }
        
        public string InvokeBitMapQueryWS(string requestParameter) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSBody();
            inValue.Body.requestParameter = requestParameter;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeBitMapQueryWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeBitMapQueryWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWS request) {
            return base.Channel.InvokeQueryWS(request);
        }
        
        public string InvokeQueryWS(string merchantId, string orderNumber, string atrn, string txntype) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.orderNumber = orderNumber;
            inValue.Body.atrn = atrn;
            inValue.Body.txntype = txntype;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeQueryWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeQueryWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWS request) {
            return base.Channel.InvokePartialCaptureWS(request);
        }
        
        public string InvokePartialCaptureWS(string merchantId, string atrn, string amount) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            inValue.Body.amount = amount;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokePartialCaptureWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokePartialCaptureWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWS request) {
            return base.Channel.InvokeCaptureWS(request);
        }
        
        public string InvokeCaptureWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeCaptureWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeCaptureWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices.InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWS request) {
            return base.Channel.InvokeFullAuthReversalWS(request);
        }
        
        public string InvokeFullAuthReversalWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeFullAuthReversalWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_live.InvokeEcomWebServices)(this)).InvokeFullAuthReversalWS(inValue);
            return retVal.Body.@return;
        }
    }
}
