//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSample.ServiceReferenceInvokeEcomWebServices_test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uilogic.dp.toml.com/", ConfigurationName="ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices")]
    public interface InvokeEcomWebServices {
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSResponse InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSResponse InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWS request);
        
        // CODEGEN: Generating message contract since element name requestParameter from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSResponse InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportResponse InvokeQueryWSTxnReport(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReport request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSResponse InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSResponse InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSResponse InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWS request);
        
        // CODEGEN: Generating message contract since element name merchantId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSResponse InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeReversalWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeReversalWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSBody Body;
        
        public InvokeReversalWS() {
        }
        
        public InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeReversalWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amount;
        
        public InvokeReversalWSBody() {
        }
        
        public InvokeReversalWSBody(string merchantId, string atrn, string amount) {
            this.merchantId = merchantId;
            this.atrn = atrn;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeReversalWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeReversalWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSResponseBody Body;
        
        public InvokeReversalWSResponse() {
        }
        
        public InvokeReversalWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeReversalWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeReversalWSResponseBody() {
        }
        
        public InvokeReversalWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeVoidWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeVoidWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSBody Body;
        
        public InvokeVoidWS() {
        }
        
        public InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeVoidWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeVoidWSBody() {
        }
        
        public InvokeVoidWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeVoidWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeVoidWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSResponseBody Body;
        
        public InvokeVoidWSResponse() {
        }
        
        public InvokeVoidWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeVoidWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeVoidWSResponseBody() {
        }
        
        public InvokeVoidWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeBitMapQueryWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeBitMapQueryWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSBody Body;
        
        public InvokeBitMapQueryWS() {
        }
        
        public InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeBitMapQueryWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestParameter;
        
        public InvokeBitMapQueryWSBody() {
        }
        
        public InvokeBitMapQueryWSBody(string requestParameter) {
            this.requestParameter = requestParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeBitMapQueryWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeBitMapQueryWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSResponseBody Body;
        
        public InvokeBitMapQueryWSResponse() {
        }
        
        public InvokeBitMapQueryWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeBitMapQueryWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeBitMapQueryWSResponseBody() {
        }
        
        public InvokeBitMapQueryWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWSTxnReport {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWSTxnReport", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportBody Body;
        
        public InvokeQueryWSTxnReport() {
        }
        
        public InvokeQueryWSTxnReport(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSTxnReportBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string txntype;
        
        public InvokeQueryWSTxnReportBody() {
        }
        
        public InvokeQueryWSTxnReportBody(string merchantId, string sDate, string eDate, string sTime, string eTime, string txntype) {
            this.merchantId = merchantId;
            this.sDate = sDate;
            this.eDate = eDate;
            this.sTime = sTime;
            this.eTime = eTime;
            this.txntype = txntype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWSTxnReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWSTxnReportResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportResponseBody Body;
        
        public InvokeQueryWSTxnReportResponse() {
        }
        
        public InvokeQueryWSTxnReportResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSTxnReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeQueryWSTxnReportResponseBody() {
        }
        
        public InvokeQueryWSTxnReportResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSBody Body;
        
        public InvokeQueryWS() {
        }
        
        public InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txntype;
        
        public InvokeQueryWSBody() {
        }
        
        public InvokeQueryWSBody(string merchantId, string orderNumber, string atrn, string txntype) {
            this.merchantId = merchantId;
            this.orderNumber = orderNumber;
            this.atrn = atrn;
            this.txntype = txntype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeQueryWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeQueryWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSResponseBody Body;
        
        public InvokeQueryWSResponse() {
        }
        
        public InvokeQueryWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeQueryWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeQueryWSResponseBody() {
        }
        
        public InvokeQueryWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokePartialCaptureWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokePartialCaptureWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSBody Body;
        
        public InvokePartialCaptureWS() {
        }
        
        public InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokePartialCaptureWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amount;
        
        public InvokePartialCaptureWSBody() {
        }
        
        public InvokePartialCaptureWSBody(string merchantId, string atrn, string amount) {
            this.merchantId = merchantId;
            this.atrn = atrn;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokePartialCaptureWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokePartialCaptureWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSResponseBody Body;
        
        public InvokePartialCaptureWSResponse() {
        }
        
        public InvokePartialCaptureWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokePartialCaptureWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokePartialCaptureWSResponseBody() {
        }
        
        public InvokePartialCaptureWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeCaptureWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeCaptureWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSBody Body;
        
        public InvokeCaptureWS() {
        }
        
        public InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeCaptureWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeCaptureWSBody() {
        }
        
        public InvokeCaptureWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeCaptureWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeCaptureWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSResponseBody Body;
        
        public InvokeCaptureWSResponse() {
        }
        
        public InvokeCaptureWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeCaptureWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeCaptureWSResponseBody() {
        }
        
        public InvokeCaptureWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeFullAuthReversalWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeFullAuthReversalWS", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSBody Body;
        
        public InvokeFullAuthReversalWS() {
        }
        
        public InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeFullAuthReversalWSBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string atrn;
        
        public InvokeFullAuthReversalWSBody() {
        }
        
        public InvokeFullAuthReversalWSBody(string merchantId, string atrn) {
            this.merchantId = merchantId;
            this.atrn = atrn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeFullAuthReversalWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeFullAuthReversalWSResponse", Namespace="http://uilogic.dp.toml.com/", Order=0)]
        public PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSResponseBody Body;
        
        public InvokeFullAuthReversalWSResponse() {
        }
        
        public InvokeFullAuthReversalWSResponse(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InvokeFullAuthReversalWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InvokeFullAuthReversalWSResponseBody() {
        }
        
        public InvokeFullAuthReversalWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvokeEcomWebServicesChannel : PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvokeEcomWebServicesClient : System.ServiceModel.ClientBase<PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices>, PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices {
        
        public InvokeEcomWebServicesClient() {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokeEcomWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvokeEcomWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWS request) {
            return base.Channel.InvokeReversalWS(request);
        }
        
        public string InvokeReversalWS(string merchantId, string atrn, string amount) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            inValue.Body.amount = amount;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeReversalWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeReversalWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeVoidWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWS request) {
            return base.Channel.InvokeVoidWS(request);
        }
        
        public string InvokeVoidWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeVoidWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeVoidWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeBitMapQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWS request) {
            return base.Channel.InvokeBitMapQueryWS(request);
        }
        
        public string InvokeBitMapQueryWS(string requestParameter) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSBody();
            inValue.Body.requestParameter = requestParameter;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeBitMapQueryWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeBitMapQueryWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeQueryWSTxnReport(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReport request) {
            return base.Channel.InvokeQueryWSTxnReport(request);
        }
        
        public string InvokeQueryWSTxnReport(string merchantId, string sDate, string eDate, string sTime, string eTime, string txntype) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReport inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReport();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.sDate = sDate;
            inValue.Body.eDate = eDate;
            inValue.Body.sTime = sTime;
            inValue.Body.eTime = eTime;
            inValue.Body.txntype = txntype;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSTxnReportResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeQueryWSTxnReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeQueryWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWS request) {
            return base.Channel.InvokeQueryWS(request);
        }
        
        public string InvokeQueryWS(string merchantId, string orderNumber, string atrn, string txntype) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.orderNumber = orderNumber;
            inValue.Body.atrn = atrn;
            inValue.Body.txntype = txntype;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeQueryWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeQueryWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokePartialCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWS request) {
            return base.Channel.InvokePartialCaptureWS(request);
        }
        
        public string InvokePartialCaptureWS(string merchantId, string atrn, string amount) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            inValue.Body.amount = amount;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokePartialCaptureWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokePartialCaptureWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeCaptureWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWS request) {
            return base.Channel.InvokeCaptureWS(request);
        }
        
        public string InvokeCaptureWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeCaptureWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeCaptureWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSResponse PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices.InvokeFullAuthReversalWS(PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWS request) {
            return base.Channel.InvokeFullAuthReversalWS(request);
        }
        
        public string InvokeFullAuthReversalWS(string merchantId, string atrn) {
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWS inValue = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWS();
            inValue.Body = new PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSBody();
            inValue.Body.merchantId = merchantId;
            inValue.Body.atrn = atrn;
            PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeFullAuthReversalWSResponse retVal = ((PGSample.ServiceReferenceInvokeEcomWebServices_test.InvokeEcomWebServices)(this)).InvokeFullAuthReversalWS(inValue);
            return retVal.Body.@return;
        }
    }
}
